[package]
name = "exif_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
img-parts = "0.3.0"
imghdr = "0.7.0"
kamadak-exif = "0.5.5"
